version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql_db:3306/${MYSQL_DATABASE}
    depends_on:
      - mysql_db
    networks:
      - app

volumes:
  mysql_data:

networks:
  app:
    driver: bridge
